### ISSUE TITLE
Use case:   science development

### ISSUE THREAD

**Issue by tclune** [pchakraborty/mepo#4]
Scientist starts from an approved tag on some fixture F, and wishes all science aspects to remain frozen as they develop some new feature.

Changes are required on repositories  X & Y.

Sequence

1.  Clone and build approved tag (detached head everywhere)
2. create and checkout new feature branches (from detached head) on repos X & Y
3. develop/test/commit repeatedly on feature branch
4. ready for merge  (all changes committed on feature branches)
    1. Catch up to development of fixture F
        1. checkout _develop_ configuration of fixture F
        2. checkout develop branches of repos X & Y
        3. checkout feature branches of X & Y
        4. merge (or rebase) X & Y feature branches onto develop branches
        5. repeat steps 3 and 4 until ready for PR
    2. Issue PR's
        1. push feature branches for X & Y to GitHub host
        2. issue PRs onto develop for feature branches
        3. do something magical for CI

**Comment by pchakraborty** [comment]
Most of these steps (except catching up to changes in develop) are now covered by v1.0.0.

**Comment by tclune** [comment]
Good.   Is that remaining "bit" problematic, hard,  straightforward, or not yet known?

**Comment by pchakraborty** [comment]
I think it will be better to deal with handling develop branches first (both specifying in repolist and assigning an appropriate command to check out) before handling the 'catch up' phase.

**Comment by pchakraborty** [comment]
This issue has been resolved. See this [wiki](../wiki/Workflow:-science-development) entry.
