### ISSUE TITLE
Use case: feature development

### ISSUE THREAD

**Issue by tclune** [pchakraborty/mepo#5]
This is very similar to issue #4 , but here we can start on the develop track.

Developer starts development of new feature on fixture F.  Changes are required on repositories X & Y.

Sequence

1.  Clone and build latest develop tag for Fixture F (detached head everywhere)
2. Checkout develop branches on repos X & Y
3  Create and checkout new feature branches on repos X & Y
3. Develop/test/commit repeatedly on feature branch
4. Ready for merge  (all changes committed on feature branches)
    1. Catch up to development of fixture F
        1. Do a fetch on repos X & Y to update develop branch
        4. merge (or rebase) X & Y feature branches onto develop branches
        5. repeat steps 3 and 4 until ready for PR
    2. Issue PR's
        1. push feature branches for X & Y to GitHub host
        2. issue PRs onto develop for feature branches
        3. do something magical for CI

**Comment by pchakraborty** [comment]
Workflow outlined in this [wiki entry](../wiki/Workflow:-feature-development). Closing.
